### ISSUE TITLE
Ambiance For Roguelike Level

### ISSUE THREAD

**Issue by stormk539** [Mattorious/Woodlands#10]
As the sound designer, I must create ambiance for the roguelike level so that the world feels alive and fluid with the gameplay. 

CoS:
1) 3 different songs that have a peaceful tune, resembling the peace of a forest
2) 7 different sounds of the forest (birds chirping, bushes moving, wind hitting trees, animals scurrying, etc.)

**Comment by samstewart21** [comment]
Ambiance still needs to be added to the new levels.
