### ISSUE TITLE
Research Tower Attacks

### ISSUE THREAD

**Issue by stormk539** [Mattorious/Woodlands#13]
As a gameplay engineer, I must begin researching how the towers will attack so that the lead artist can begin to design the towers to how they will attack. 

CoS: 
1) Have 8 different attacks in mind for the meeting next week. This can be concept sketches, videos, inspirations, or anything that would convey a woodland tower attack. 
2) Google doc created explaining ideas

**Comment by NeogearNeon** [comment]
Proper tower attack information completed. They can be found on my scratch paper google doc.
