### ISSUE TITLE
Sketch Level Outlines

### ISSUE THREAD

**Issue by stormk539** [Mattorious/Woodlands#16]
As the level designer, I need to sketch out the layout of the levels so that after the artist gets done creating the assets, I can begin to design the level.

CoS:
1) 5 Completed Level Sketches 
2) Annotated for where assests go (EX. "Tree goes here" with a line that points to where the tree goes)  
3) Make sure the size for each sketch is about the size of a sheet of paper

**Comment by stormk539** [comment]
As the level designer, I need to sketch out the layout of the levels so that after the artist gets done creating the assets, I can begin to design the level.

CoS:
1) 5 Completed Level Sketches 
2) Annotated for where assests go (EX. "Tree goes here" with a line that points to where the tree goes)

**Comment by samstewart21** [comment]
Level sketches are complete.
