### ISSUE TITLE
Top-Down Layout + Map

### ISSUE THREAD

**Issue by stormk539** [Mattorious/Woodlands#27]
As a gameplay engineer, I must create the top-down layout for the tower defense portion of the game so that the player can see the entire level in the gameplay. Additionally, I must also create one map for the first sprint. 
CoS:
1) Make league of legends style map for the tower defense game in UE4
2) Top down camera angle

**Comment by NeogearNeon** [comment]
Layout plans and array plans are completed. Next will be creating the temporary assets for the prototype and placing them into UE.
