### ISSUE TITLE
Additional Sound and Sound Editing 

### ISSUE THREAD

**Issue by stormk539** [Mattorious/Woodlands#29]
As the sound designer, I must edit the sounds already found so that the gameplay engineer can properly place the ambiance in the game. Additionally, I must make sure those files are wav files so that the gameplay engineer can import the sounds into UE4. 

CoS: 
1) All the audio is converted to .wavs
2) Trim down the longer audio bits 
3) Find any extra ambiance in areas that are lacking 
4) Find music for the tower defense section
5) Find/make projectile noises

**Comment by samstewart21** [comment]
All ambience sounds have been converted to .wavs.

**Comment by samstewart21** [comment]
Roguelike sounds have been converted to .wavs

**Comment by samstewart21** [comment]
Created a list of tracks that we could possibly use for the Tower Defense section of the game.
