### ISSUE TITLE
Basic Main Menu 

### ISSUE THREAD

**Issue by stormk539** [Mattorious/Woodlands#34]
CoS: 
1) Working start and exit buttons 
2) Dynamic background 
3) All buttons have the art applied

**Comment by samstewart21** [comment]
Start and exit buttons work. Buttons have had the art applied to them.

**Comment by samstewart21** [comment]
Button art need to be added to buttons on new menu.

**Comment by samstewart21** [comment]
> Start and exit buttons work. Buttons have had the art applied to them.
** 2/4/21 Update:** Button art needs to be applied to the new menu with the dynamic background.

**Comment by samstewart21** [comment]
### 2/7/21 Update:
Button art has been applied to the new menu with the dynamic background. 

**Pull Request #47**

**Comment by samstewart21** [comment]
The button art for the options button needs to be added to the main menu.
