### ISSUE TITLE
Main Menu 

### ISSUE THREAD

**Issue by stormk539** [Mattorious/Woodlands#5]
As the UI Designer, I must create the main menu for the game so that the player has the option to start the game, edit the options, or exit the game. 

CoS: 
1) Working start, options, and exit button 
2) Interactive element 
3) Completed art for main menu
4) Audio

**Comment by samstewart21** [comment]
Start, option and exit buttons have been added. 

[Pull Request](https://github.com/Mattorious/Woodlands/pull/21)

**Comment by samstewart21** [comment]
Button art has been added to the start and exit buttons.

**Comment by samstewart21** [comment]
### 2/7/21 Update:
Button art has been added to the start and exit buttons on the new main menu with the dynamic background. (Pull Request: #47) Button art for the options button needs to be created. The logo has also been added to the new main menu.
