### ISSUE TITLE
Ambient Audio

### ISSUE THREAD

**Issue by stormk539** [Mattorious/Woodlands#50]
As the audio engineers, we must create our own audio so that we can sell our game commercially to make some money. Plus, we the audio will help add personality to every level. 

CoS:
1) Audio is created by the audio engineers
2) Bird sounds, wind rustling leaves, crunching leaves, mystical sounding effects, look at the google drive and make sounds based off of the other sounds (but make them yourself!)
3) All files are .ogg files and edited to sound great

**Comment by samstewart21** [comment]
Ambient audio has been recorded, edited and uploaded.

**Comment by samstewart21** [comment]
Roguelike Soundtrack has been edited and uploaded.
