### ISSUE TITLE
2D Weapon Pickup Art

### ISSUE THREAD

**Issue by stormk539** [Mattorious/Woodlands#73]
As an artist, I must craft 2D weapons for the player to pickup so that the player does not feel like they are using the same weapons over and over again. 

CoS: 
1) 10 different weapon art for the player to pick up
2) Theme of weapons are related to plushie, cute, or woodland related (Needle Sword, Twig shiv, Acorn shield, etc.)
3) Must be as close to Katie's original art style as possible

**Comment by NeogearNeon** [comment]
8 Items uploaded. I ran out of ideas and everything else I tried to do was super low quality.
