### ISSUE TITLE
Player Character, Environment, and Soundtrack audio

### ISSUE THREAD

**Issue by stormk539** [Mattorious/Woodlands#76]
As sound engineers, we must place the audio created in the level so that the player is more immersed in the world we have made, as well as make the world feel more alive/active.

CoS:
1) Player character has the hit cries, attack sound, excitement when picking up item, and death grunt
2) Levels have ambient audio added
3) Roguelike has a soundtrack that is randomized

**Comment by samstewart21** [comment]
Added music and ambiance audio files to RogueLike  tiles. 

Pull Request #94

**Comment by samstewart21** [comment]
Added tower defense music audio files to both tower defense maps. 

Pull Request #95
