### ISSUE TITLE
Tower Defense Soundtrack

### ISSUE THREAD

**Issue by stormk539** [Mattorious/Woodlands#77]
As the sound designers, we must create a soundtrack for the tower defense portion of the game so that the player is not disturbed by the lack of music in the level. 

CoS:
1) Three created songs that can be intense or cutesy (one or the other, not a mix: Pick either orchestra or cutesy wind chimes)
2) Songs are .ogg files 
3) Must be created by us!

**Comment by samstewart21** [comment]
Windchime soundtrack files have been uploaded.
