### ISSUE TITLE
Organized GitHub Issues 

### ISSUE THREAD

**Issue by samstewart21** [Mattorious/Woodlands#79]
Organized GitHub issues by closing out issues that have been completed. Used the GitHub milestones feature to group issues together so that they will be easily sortable by the different phases of the project (prototype, alpha, etc.)

**CoS:**
Issues that have been completed should be closed using the Close issue or Close issue with comment features on GitHub. 
Milestones should be created for each phase of the project so that issues can be grouped with the phase of the project they were created in and sorted through easier (prototype, alpha,etc.)

**Comment by samstewart21** [comment]
Old issues have been closed and milestones have been created.

**Comment by stormk539** [comment]
Thank you! I went ahead and added the current issues to the Alpha milestone, in addition to user stories for this sprint's issues.
