### ISSUE TITLE
Roguelike Soundtrack: Music

### ISSUE THREAD

**Issue by stormk539** [Mattorious/Woodlands#81]
As a sound designer, I need music for the game so that the player can get amped up to fight enemies! 

CoS:
1) 5 SONGS (Royalty free is fine)
2) Songs must be upbeat and orchestra-like
3) Files must be .ogg

**Comment by RossWoods41** [comment]
Finished creating two looping tracks each for the tower defense and roguelike sections of them game, as well as the mystical sound effect. All OGG files are in Google Drive.

**Comment by samstewart21** [comment]
Uploaded public domain/royalty free music to Google Drive.
